### ISSUE TITLE
Add `info.lifecycle` with maturity/lifecycle informations.

### ISSUE THREAD

**Issue by ioggstream** [OAI/sig-lifecycle#7]
## The proposal

A `LifeCycle` object to describe the API lifecycle, eg:

```
info:
  lifecycle:
    maturity: published   # or deprecated,  retired, ...
    published_at: 2019-01-01
    deprecated_at: 2022-01-01
    retired_at: 2022-06-01
```

Data related to other version may be specified eg. via link relations

```
    links:
    - rel: prev
      url: https://prev-oas-spec
    - rel: next
      url: https://next-oas-spec

```

## Benefits

Automatic discovery of API status.

## Considerations

- http://apisjson.org/ seems not maintained anymore
- we already have `deprecation` informations in operations
- lifecycle could contain further informations related to eg. versioning (link to previous spec versions)

## Related to

OAI/sig-lifecycle#8
